Prettify API by not separating teasers by domain
ropfoo/tonemato pull request #31
Opened 2023-04-19 21:42 UTC by robinduerhager

With the current PR implementation, Drilbur sends one big array of teasers:

```js
[ { teaser }, { teaser }, ... ]
```

Ralts then saves that Array via a `data` key.

2023-04-29 10:45 UTC, ropfoo requested changes

2023-04-29 10:45 UTC, ropfoo commented on apps/ralts/src/cache/update-cache.ts
> +      'data',
maybe instead of `data` we should be more descriptive here (like `scrapeData` or just `scrape`) since we probably gonna have mulitple cache keys (eg. different instruments) later on

2023-04-29 10:45 UTC, ropfoo commented on apps/ralts/src/cache/get-cache.ts
Dont really think we need this function anymore..
running:
```ts
JSON.parse(await redis.get('data'))
```
is simple enough imo.
getCache might even be misleading.. the alternative would be to call the function sometihin like `getDataCache`

2023-04-29 21:57 UTC, robinduerhager commented on apps/ralts/src/cache/update-cache.ts
> +      'data',
How about "raw", since this is actually kind of untransformed until this point?

2023-05-06 15:19 UTC, ropfoo approved these changes

2023-05-06 16:45 UTC, merged